package pl.lasota.crm.enums;

public enum PrivilegeName {
    MANAGE_OWN_ACCOUNT, //GET UPDATE DELETE
    MANAGE_ANY_ACCOUNT, //GET UPDATE DELETE
    SEARCH_ANY_ACCOUNTS, //SEARCH
    SUSPEND_RESTORE_ANY_ACCOUNT, //SUSPEND RESTORE

    TASK_MANAGEMENT

}
